language: node_js
node_js:
- "0.10.36"
install:
- npm install
before_script:
  - chmod +x deploy.sh
script:
  - npm test
sudo: false
deploy:
- provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: dev
- provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: release
- provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master

env:
  matrix:
    - CXX=g++-4.8
  global:
    - SAMPLE_ENV_VAR1="check yourself before you wreck yourself"

    # DEV_AWS_KEY
    - secure: sETz8w0h7y8QwDwyy+LFjdFfP42jYF6ES42D5scs9FcHD/Czb/7kLAEK1lV+K+f9yoZINziAUuDmKAmGGYG/5X0vUEJyhOTbEi2Kv6xavZ7wUneNhb53wH0H0JJi2iVlimzYFBKvwWgFwY1ltQ5YKTRyubBeZQU94XLaWUQYNhXSou9u0vnK40X2D6epbnvRkDhe7GBsd6EBFLWFFKB6GGKqApxrcfMekthVuUcYJoyPN2NbhUQarKQAPhvsvoIdR8h1a6C6KDqV23yqMFT7+EFS8Q6lIhioevAz/w7m45577nJnajtdHDlvMnM+saNiNwwIjoif3hJ6d1Omf36NfCTL1TzcLI8sNkegok0UO++2eOvGNbwFbc2xrO1+180DUf33uyKU3DDO4avaVaiocSusxfLcqY2v56puAykcTtZU218ZcAF6ZmqRlQLonjCTHOS77Fkn5lurZ0XYor2rvN3GeVXRp9eEi7tDOfrg7oz5GdQC1Ea9BXAw49wisEbYbw/vvxyXrHdC5wshERDpuI89Nkug1/Z9Irsf/TMBCbGWjuZsGeLzQfzQAbWB6rRIuCe7BaWR4nYzneJZAXlRJoR3IHFya/dgIIEHoCDiuHgZuTELgdKjbpm0hOjPEs2Z1ZK9z331EdBbVAvhwC76pUx3wu0TW89zZzcApT2DXC0=
    # DEV_AWS_SECRET
    - secure: thX9gw6KXfL1O+FTfgiXScRt54cJzTEmpCWn7FXzpZT8uoPrrWLN4c6XioOZ1JVFD0VYsdua8Nvj7Byj8/etxP8VTyxSAuGTtZW3MCMzdVlxQMD+s2a1UxgFz1rRRHJjJQkddpvrPmKYL62w3bzqyYAaXFsLZMPoZVK93rdOzryGjliLMo+9uPmqiY7svQzav6H1Oof9FuMi64la/PfzPdnyxqkukaXGzv9JEMakbj2Dc4n3hDSsT6ErtzO/Uttv3mZEmQLZua4Gz3dGzhrqUqAZGitsjEHIcKUdeUG6Km9TqJI21eLI0o6meFSv1HXb+w4Ag0o/xqC6Ua1cL4F5CfOUtlyMAgEYUovCaaoHLijqLXzQIgqZ98Aw7edbPjKiZyQoF1S72IaNFO2vYqLS/TovYVViPGSCP6pMbSTifHhptyc46IJBvBFIJrSJI9yZ8LHXKHSjcrzM3CQgtGN2TQRMnvGI1+qR5dpQp31vKdeUF+TZz84QZbh5HVmR9iHNQvAO8O/I9bW73ZaTJ0VNwINRmEUGl5ZLExLpVg54ixZKrlInxJFB7RVKj2Fme9rKWRv/5maPZZBxCvw4ZW3RUI9vf/SlPvgO8JiW1EcCP099iAJuNc6xOr2zdnfofHdcKO5hiOC0KmU1YBa4Xx0vXsKtx3jupPc138+fvjC3bpk=
    # AWS_LAMBDA_ROLE_ARN
    - secure: BC0IIWzz/y3hW26SUj6TwSVR2lwjEAo96U7eJlmV2HjCmkbU6DzFLUqh35kYIoo0bdvK2LkDx3cQq+8vS7Nej0P0xFiZWFDH+wMKWj7bpjnQOBY5Ixh5mf7BJDCVgvDD2DJ+K6Ziz7i7hO2CUpX20JtCFsih45U959btm0Sb/IJ7pelC5vRLj2OTEnOxezZxof3r5GQNxLoBCnBM+i4IIFNiqxUUJQCmEQtxFjhxe5gDtWRu9QT6/w+dzehrYW2a97FRe9NXOQDzDmOJ1lDmR4bQ4he/NdQ+/laYQb/2+VKVIMk1vcPGbr/kgIT8Z6PDLCXvXT2Ary3r+F0/gxcrcd7J3nLOXdGnSmb3U/Mji/lA+XwKE6/c0slEukUBVSAEU/aRH7pLbtTbwFs4fIYn7FAriKd+VC/9EJ8atDn9kVJcAX5EGYP7VRRLf+RHqkP9vt9XwTEO7+I+B86dHiPgbe4RBk/daJSK4QigYUT+AiQH8NXfEpvxYSJP0LYSzV170CVYn5TwFa64aJtNrV8yj5sshlCh0Vuo0SgyGGnrH+a1UpK0OPgniKhV4rbcrzLh45XyOCAWwjFJ/4pEp+LL6zjuERYUX3Bh8rdKtH6ViKO+J2t4e9gMB+p6EhOKyI95o0ryfZqOO9Br11+uqPbqLEf19qirm+M1k9z1+2xRSlA=



